POST https://node-do-zero-rocketseat.onrender.com/videos
Content-Type: application/json


{
  "title":"Video novo testando",
  "description":"Esse é o primeiro video",
  "duration":180
}



###


GET https://node-do-zero-rocketseat.onrender.com/videos


###

PUT https://node-do-zero-rocketseat.onrender.com/videos/95f01f8c-99b5-464e-9abe-1eb6e8fca2da
Content-Type: application/json


{
  "title":"Video 01",
  "description":"Esse é o primeiro video",
  "duration":180
}


###

DELETE https://node-do-zero-rocketseat.onrender.com/videos/2796b70f-cc4f-4ccc-9189-d7ed2878228e